"""Build/verify Court Init's finite vanilla-role dispatch against an installed CK3.

Run with --check after updating CK3. Unknown roles fail rather than silently
claiming support. The checked-in dispatch needs no Python at runtime.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "common"

# Constrained jobs precede general ones. Highest raw aptitude is selected within
# each job in this stable order; this is not a global assignment optimizer.
# Maxima are reviewed against vanilla so one failed recruit never loops forever.
ROLES = {
    "favored_minister": 1,
    "garuda": 2,
    "chief_eunuch": 1,
    "cave_hermit": 1,
    "court_guru": 1,
    "court_brahmin": 1,
    "chief_qadi": 1,
    "master_assassin": 1,
    "court_artificer": 3,
    "akolouthos": 1,
    "khlon_glan": 1,
    "wet_nurse": 1,
    "lady_in_waiting": 2,
    "keeper_of_the_harem": 1,
    "court_astrologer": 1,
    "boyan": 1,
    "siege_engineer": 1,
    "yurtchi": 1,
    "cherbi": 1,
    "yeke_jarquchi": 1,
    "foreign_emissary": 1,
    "keeper_of_the_horses": 1,
    "charioteer": 1,
    "bookmaker": 1,
    "court_brewmaster": 1,
    "executioner": 1,
    "court_physician": 1,
    "travel_leader": 1,
    "court_tutor": 1,
    "bodyguard": 2,
    "food_taster": 1,
    "seneschal": 1,
    "antiquarian": 1,
    "court_scholar": 1,
    "court_gardener": 1,
    "court_poet": 1,
    "court_musician": 1,
    "court_jester": 1,
    "cupbearer": 1,
    "grand_preceptor": 1,
    "grand_mentor": 1,
    "grand_guardian": 1,
    "fire_dragon_engineer": 1,
    "eparch": 1,
    "minister_bureaucrat": 2,
    "champion": 1,
    "master_of_hunt": 1,
    "master_of_horse": 1,
    "royal_architect": 1,
    "cultural_emissary": 1,
    "chronicler": 1,
    "high_almoner": 1,
    "keeper_of_swans": 1,
}


def installed_roles(game: Path) -> dict[str, int]:
    found = {}
    for source in (game / "common" / "court_positions" / "types").glob("*.txt"):
        # Definitions start at column zero in vanilla; a role's fixed slot cap
        # occurs before its next top-level definition. Camp offices stay separate.
        raw = source.read_text(encoding="utf-8-sig")
        for match in re.finditer(
            r"^(\w+)_court_position\s*=\s*\{(.*?)(?=^\w+\s*=\s*\{|\Z)",
            raw, re.M | re.S,
        ):
            cap = re.search(r"^\s*max_available_positions\s*=\s*(\d+)", match[2], re.M)
            if not cap:
                raise ValueError(f"Review nonconstant/missing capacity for {match[1]} in {source}")
            found[match[1]] = int(cap[1])
    if not found:
        raise ValueError(f"No vanilla court-position definitions under {game}")
    return found


def artifacts() -> dict[Path, str]:
    header = "# Generated by tools/build_court_roles.py. Camp offices are excluded.\n"
    effect = header + "ca_court_init_effect = {\n"
    effect += "\tsave_scope_as = ca_court_init_employer\n"
    for counter in ("filled", "generated", "unfilled"):
        effect += f"\tset_variable = {{ name = ca_court_init_{counter} value = 0 }}\n"
    for role, cap in ROLES.items():
        effect += f"\tca_court_init_fill_type_effect = {{ POSITION = {role}_court_position CAPACITY = {cap} }}\n"
    effect += "\tremove_variable = ca_court_init_slots_to_fill\n"
    effect += "\tclear_saved_scope = ca_court_init_type\n\tclear_saved_scope = ca_court_init_employer\n}\n"
    # hidden_effect still walks its effects while generating decision tooltips.
    # This native container skips that walk: runtime-created variables and
    # characters do not exist when a player merely previews the decision.
    body = effect[len(header + "ca_court_init_effect = {\n"):-2]
    effect = (header + "# Skip tooltip simulation of runtime-created variables and characters.\n"
              + "ca_court_init_effect = {\n\thidden_effect_new_object = {\n"
              + "".join("\t" + line for line in body.splitlines(keepends=True))
              + "\t}\n}\n")
    trigger = header + "ca_court_init_has_vacancy_trigger = {\n\tOR = {\n"
    for role in ROLES:
        trigger += f"\t\tcan_employ_court_position_type = {role}_court_position\n"
    trigger += "\t}\n}\n"
    return {
        MOD / "scripted_effects" / "ca_court_init_roles_effects.txt": effect,
        MOD / "scripted_triggers" / "ca_court_init_triggers.txt": trigger,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True, help="CK3's game directory")
    parser.add_argument("--check", action="store_true", help="Read-only source coverage and drift check")
    args = parser.parse_args()
    actual = installed_roles(args.game_root)
    missing, stale = actual.keys() - ROLES.keys(), ROLES.keys() - actual.keys()
    changed = {k: (ROLES[k], actual[k]) for k in actual.keys() & ROLES.keys() if ROLES[k] != actual[k]}
    if missing or stale or changed:
        raise SystemExit(f"Role review required: missing={sorted(missing)}, stale={sorted(stale)}, changed={changed}")
    for path, text in artifacts().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != text:
                raise SystemExit(f"Generated dispatch differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8-sig", newline="\n")
    print(f"Court Init: {len(ROLES)} vanilla role types / {sum(ROLES.values())} total defined slots covered; camp offices excluded.")


if __name__ == "__main__":
    main()
