"""Generate Court Automation salary adapters from the installed vanilla salary blocks.

These adapters evaluate the game's own salary values in the employer context.
They do not duplicate salary formulas or calculate task costs. The full-court
estimate prices vacancies at today's rates; appointment-dependent discounts may
change the result. Use --check to detect a changed game salary schema/content.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re

from build_court_roles import MOD, ROLES, installed_roles


CURRENCIES = ("gold", "treasury", "prestige", "piety")


def block(text: str, opening: int) -> tuple[str, int]:
    """Return a balanced brace body, ignoring comments and quoted strings."""
    assert text[opening] == "{"
    depth, quoted, escaped, comment = 1, False, False, False
    for pos in range(opening + 1, len(text)):
        c = text[pos]
        if comment:
            if c == "\n":
                comment = False
            continue
        if quoted:
            if escaped:
                escaped = False
            elif c == "\\":
                escaped = True
            elif c == '"':
                quoted = False
            continue
        if c == "#":
            comment = True
        elif c == '"':
            quoted = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1:pos], pos + 1
    raise ValueError("Unbalanced source block")


def salary_fields(game: Path) -> dict[str, dict[str, str]]:
    found = {}
    for source in (game / "common" / "court_positions" / "types").glob("*.txt"):
        raw = source.read_text(encoding="utf-8-sig")
        for match in re.finditer(r"^(\w+)_court_position\s*=\s*\{", raw, re.M):
            role = match[1]
            definition, _ = block(raw, raw.index("{", match.start()))
            salary_match = re.search(r"^\tsalary\s*=\s*\{", definition, re.M)
            if not salary_match:
                raise ValueError(f"Missing salary: {role}")
            salary, _ = block(definition, definition.index("{", salary_match.start()))
            fields = {}
            for field in re.finditer(r"^\t\t(\w+)\s*=\s*", salary, re.M):
                key = field[1]
                if key == "round":
                    continue
                if key not in CURRENCIES:
                    raise ValueError(f"Review new salary currency {role}.{key}")
                if salary[field.end()] == "{":
                    expression, _ = block(salary, field.end())
                    # Normalize only indentation, retaining native expressions.
                    lines = expression.strip("\r\n").splitlines()
                    if lines and not lines[-1].strip():
                        lines.pop()
                    expression = "\n".join(line[3:] if line.startswith("\t\t\t") else line.lstrip("\t") for line in lines)
                else:
                    value = salary[field.end():].splitlines()[0].split("#", 1)[0].strip()
                    expression = "value = " + value
                fields[key] = expression.strip()
            found[role] = fields
    if found.keys() != ROLES.keys():
        raise ValueError(f"Salary coverage mismatch: {found.keys() ^ ROLES.keys()}")
    return found


def indent(text: str, level: int = 1) -> str:
    return "\n".join("\t" * level + line if line else "" for line in text.splitlines())


def adapters(fields: dict[str, dict[str, str]]) -> str:
    out = [
        "# Generated by tools/build_court_salaries.py from vanilla salary fields.",
        "# Owner/character scope API: ca_court_salary_<short_role>_<currency>.",
        "# Values set temporary scope:liege to the owner, as native salaries require.",
        "# Base salaries only: active court-position task costs are separate.",
        "# Full estimates keep current conditions and price all current vacancies.",
        "# Family/hooks/event terms can change after appointments; this is not a quote.",
        "",
    ]
    for role in ROLES:
        for currency in CURRENCIES:
            name = f"ca_court_salary_{role}_{currency}"
            if currency not in fields[role]:
                out.append(f"{name} = 0\n")
                continue
            out += [f"{name} = {{", "\tsave_temporary_scope_as = liege", indent(fields[role][currency]), "}", ""]
        out += [
            f"ca_court_salary_{role}_vacancies = {{",
            "\tvalue = 0",
            "\tif = {",
            f"\t\tlimit = {{ can_employ_court_position_type = {role}_court_position }}",
            f"\t\tvalue = {ROLES[role]}",
            f"\t\tevery_court_position_holder = {{ type = {role}_court_position subtract = 1 }}",
            "\t\tmin = 0",
            "\t}",
            "}",
            "",
        ]
    for currency in CURRENCIES:
        out += [f"ca_court_salary_current_{currency} = {{", "\tvalue = 0", "\tsave_temporary_scope_as = ca_salary_owner"]
        for role in ROLES:
            if currency not in fields[role]:
                continue
            out += [
                "\tevery_court_position_holder = {",
                f"\t\ttype = {role}_court_position",
                f"\t\tscope:ca_salary_owner = {{ add = ca_court_salary_{role}_{currency} }}",
                "\t}",
            ]
        out += ["}", "", f"ca_court_salary_additional_{currency} = {{", "\tvalue = 0"]
        for role in ROLES:
            if currency not in fields[role]:
                continue
            out += [
                "\tif = {",
                f"\t\tlimit = {{ can_employ_court_position_type = {role}_court_position }}",
                f"\t\tadd = {{ value = ca_court_salary_{role}_{currency} multiply = ca_court_salary_{role}_vacancies }}",
                "\t}",
            ]
        out += [
            "}", "",
            f"ca_court_salary_full_{currency} = {{",
            f"\tvalue = ca_court_salary_current_{currency}",
            f"\tadd = ca_court_salary_additional_{currency}",
            "}", "",
        ]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if installed_roles(args.game_root) != ROLES:
        raise SystemExit("Review role coverage/capacities with build_court_roles.py first")
    fields = salary_fields(args.game_root)
    text = adapters(fields)
    path = MOD / "script_values" / "ca_court_salary_values.txt"
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8-sig") != text:
            raise SystemExit(f"Salary adapters differ from installed vanilla: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8-sig", newline="\n")
    used = sorted({key for role in fields.values() for key in role})
    print(f"Salary adapters: {len(fields)} types; native currencies {', '.join(used)}; piety API zero where absent.")


if __name__ == "__main__":
    main()
