"""Build/check AI vacancy priorities against the installed CK3 scripts.

Only the position-level desire is reproduced. Candidate hiring remains with
native AI because its score includes undocumented engine-populated values.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re

from build_court_roles import MOD, ROLES, installed_roles
from build_court_salaries import block, indent


def artifacts(game: Path) -> dict[Path, str]:
    if installed_roles(game) != ROLES:
        raise ValueError("Review changed native role coverage/capacities first")
    scores = {}
    for source in (game / "common/court_positions/types").glob("*.txt"):
        raw = source.read_text(encoding="utf-8-sig")
        for match in re.finditer(r"^(\w+)_court_position\s*=\s*\{", raw, re.M):
            definition, _ = block(raw, raw.index("{", match.start()))
            score_match = re.search(r"^\s*ai_position_score\s*=\s*\{", definition, re.M)
            if not score_match:
                raise ValueError(f"Missing position desire: {match[1]}")
            body, _ = block(definition, definition.index("{", score_match.start()))
            scopes = set(re.findall(r"scope:(\w+)", body))
            if scopes - {"liege"}:
                raise ValueError(f"Review new position-score scopes: {match[1]} {scopes}")
            lines = body.strip("\r\n").splitlines()
            if lines and not lines[-1].strip():
                lines.pop()
            scores[match[1]] = "\n".join(line[2:] if line.startswith("\t\t") else line for line in lines)
    if scores.keys() != ROLES.keys():
        raise ValueError("Position desire coverage mismatch")
    header = "# Generated by tools/build_court_ai.py from native ai_position_score.\n"
    values = header
    dispatch = header + "ca_ai_select_court_role_effect = {\n"
    for role in ROLES:
        values += f"\nca_ai_{role}_position_score = {{\n\tsave_temporary_scope_as = liege\n{indent(scores[role])}\n}}\n"
        # A favored minister must already hold a council seat. A Garuda requires
        # forced knight-roster changes: conservative yearly help avoids both.
        if role not in {"favored_minister", "garuda"}:
            dispatch += f"\tca_ai_consider_court_role_effect = {{ ROLE = {role} }}\n"
    dispatch += "}\n"
    return {
        MOD / "script_values/ca_ai_position_values.txt": values,
        MOD / "scripted_effects/ca_ai_role_dispatch_effects.txt": dispatch,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in artifacts(args.game_root).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != content:
                raise SystemExit(f"Generated AI adapter differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8-sig", newline="\n")
    print("AI support: 53 native position priorities checked; 51 supported recruitment roles.")


if __name__ == "__main__":
    main()
